# Generated by Django 4.2 on 2023-04-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
