# Generated by Django 4.2.3 on 2023-07-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='quizapp.answer'),
        ),
    ]
