# Generated by Django 4.2.3 on 2023-07-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quiz_correct_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answers',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
