# Generated by Django 4.2.3 on 2023-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_quiz_correct_answers_quiz_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answers',
            field=models.CharField(blank=True, choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=250, null=True),
        ),
    ]
