# Generated by Django 4.2.3 on 2023-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
