# Generated by Django 4.2.3 on 2023-07-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_level_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizapp.category'),
            preserve_default=False,
        ),
    ]
