# Generated by Django 4.2.3 on 2023-07-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_level_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='category',
        ),
    ]
